# Generated by Django 5.0.3 on 2024-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=2048, null=True)),
                ('source_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('author', models.CharField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(max_length=2048)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('url_to_image', models.URLField(blank=True, max_length=2048, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
